### ISSUE TITLE
Openpose for  instrument recognition

### ISSUE THREAD

**Issue by dreamercv** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#143] opened 2021-03-09 06:21 UTC
I use Openpose for instrument identification, I modified the relevant code according to the `README`,it is work on training ,but some error arised when val during training. i think  some code  was forgotten to modify, but l cannot find code which is  forgotten to modify. so l want to ask you how to modify other code such as in `keypoints.py`.

**Comment by Daniil-Osokin** [comment] 2021-03-09 19:41
Duplicate of #141.

**Closed by Daniil-Osokin** 2021-03-09 19:41 UTC
